# Generated by Django 3.2.9 on 2021-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=255)),
                ('lastname', models.CharField(db_column='lastName', max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.IntegerField()),
                ('phonenumber', models.IntegerField(db_column='phoneNumber')),
                ('cellnumber', models.IntegerField(blank=True, db_column='cellNumber', null=True)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
    ]
