# Generated by Django 3.2.5 on 2021-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('clientid', models.IntegerField(db_column='clientId', verbose_name='Users')),
                ('traderid', models.IntegerField(db_column='traderId', verbose_name='Users')),
                ('commissiontype', models.CharField(db_column='commissionType', max_length=255)),
                ('totalamount', models.FloatField(db_column='totalAmount')),
                ('commissionamount', models.FloatField(db_column='commissionAmount')),
                ('ordertype', models.CharField(db_column='orderType', max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('btcamount', models.FloatField(db_column='btcAmount')),
                ('btcrate', models.FloatField(db_column='btcRate')),
                ('walletid', models.IntegerField(db_column='walletId', verbose_name='Wallet')),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
    ]
