# Generated by Django 3.2.5 on 2021-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_tid', models.IntegerField(db_column='tid')),
                ('st_clientId', models.IntegerField()),
                ('st_traderId', models.IntegerField()),
                ('st_commissionType', models.CharField(max_length=256)),
                ('st_totalAmount', models.FloatField()),
                ('st_commissionAmount', models.FloatField()),
                ('st_orderType', models.CharField(max_length=256)),
                ('st_status', models.CharField(max_length=256)),
                ('st_date', models.IntegerField()),
                ('st_btcAmount', models.FloatField()),
                ('st_btcRate', models.FloatField()),
                ('st_walletId', models.IntegerField()),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
