# Generated by Django 3.2.5 on 2021-11-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='st_tid',
        ),
    ]
