# Generated by Django 3.2.5 on 2021-11-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_transaction_st_tid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='st_btcAmount',
            new_name='btcAmount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_btcRate',
            new_name='btcRate',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_clientId',
            new_name='clientId',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_commissionAmount',
            new_name='commissionAmount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_commissionType',
            new_name='commissionType',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_orderType',
            new_name='orderType',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_totalAmount',
            new_name='totalAmount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_traderId',
            new_name='traderId',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='st_walletId',
            new_name='walletId',
        ),
    ]
