# Generated by Django 3.2.5 on 2021-12-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20211129_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': False},
        ),
    ]
